apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 2048-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: 2048-sa
